# Generated by Django 3.1.4 on 2020-12-08 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_profile_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
