# Generated by Django 3.1.4 on 2020-12-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201208_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='kpi',
            field=models.TextField(default='maven office '),
        ),
    ]
