# Generated by Django 3.1.4 on 2020-12-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201208_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
