# Generated by Django 3.1.4 on 2020-12-08 09:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.CharField(max_length=255)),
                ('outtime', models.CharField(max_length=255)),
                ('kpi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('absent', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
    ]
