# Generated by Django 3.1.4 on 2020-12-10 06:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='intime',
            field=models.CharField(default='10:00 AM', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='outtime',
            field=models.CharField(default='05:00 PM', max_length=255),
        ),
    ]
