# Generated by Django 3.1.4 on 2020-12-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201210_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
